# Generated by Django 5.2.4 on 2026-01-25 14:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(verbose_name='Goal')),
                ('goal_ru', models.TextField(null=True, verbose_name='Goal')),
                ('goal_en', models.TextField(null=True, verbose_name='Goal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start date')),
                ('duration_days', models.IntegerField(default=7, verbose_name='Duration (days)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20, verbose_name='Status')),
                ('current_day', models.IntegerField(default=1, verbose_name='Current day')),
                ('color', models.CharField(max_length=7, verbose_name='Color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='Day number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='challenges.challenge', verbose_name='Challenge')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['day_number', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['user', 'status'], name='challenges__user_id_441a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['user', '-created_at'], name='challenges__user_id_fc7a90_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['challenge', 'day_number'], name='challenges__challen_3b1d61_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['challenge', 'is_completed'], name='challenges__challen_5f13e9_idx'),
        ),
    ]
