# Generated by Django 5.2.4 on 2025-11-13 11:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(verbose_name='Цель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Дата начала')),
                ('duration_days', models.IntegerField(default=7, verbose_name='Длительность')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершенный'), ('abandoned', 'Отмененный')], default='active', max_length=20)),
                ('current_day', models.IntegerField(default=1, verbose_name='Текущий день')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Челлендж',
                'verbose_name_plural': 'Челленджи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='День №')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='challenges.challenge', verbose_name='Челлендж')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['day_number', 'order'],
            },
        ),
    ]
