# Generated by Django 5.2.4 on 2026-02-08 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['user', 'status', '-created_at'], name='challenges__user_id_ba4f39_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['challenge', 'day_number', 'order'], name='challenges__challen_9be16c_idx'),
        ),
    ]
