# Generated by Django 5.2.4 on 2025-11-08 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_task_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала'),
        ),
    ]
