# Generated by Django 5.2.4 on 2026-01-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_goal_en_challenge_goal_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет'),
        ),
    ]
