# Generated by Django 5.2.4 on 2026-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Цвет'),
        ),
    ]
