# Generated by Django 5.2.4 on 2025-11-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_challenge_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='current_day',
            field=models.IntegerField(default=1, verbose_name='Текущий день'),
        ),
    ]
