# Generated by Django 5.2.4 on 2026-02-12 18:49

import uuid
from django.db import migrations, models


def fill_tokens(apps, schema_editor):
    EmailVerification = apps.get_model("users", "EmailVerification")
    for record in EmailVerification.objects.all():
        record.confirm_token = uuid.uuid4()
        record.cancel_token = uuid.uuid4()
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_display_name_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="cancel_token",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="confirm_token",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(fill_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="emailverification",
            name="cancel_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="confirm_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(
                blank=True, default="User", max_length=150, verbose_name="Display name"
            ),
        ),
    ]
