# Generated by Django 5.2.4 on 2026-03-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='old_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
