# Generated by Django 5.2.4 on 2026-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailverification_old_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='max_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
